Rename /etc/sysconfig/init_params to /etc/sysconfig/rc.site. Move network services to /lib/services. Move init-functions to /lib/lsb. Make /lib/lsb a symlink to /lib/services. Create convenience symlink /etc/init.d->/etc/rc.d/init.d Add help and man pages to ifup/ifdown.
Append /run/var/bootlog to /var/log/boot.log at the end of
the boot sequence.

Add capability to step through the boot scripts at boot time.

Optionally allow environment variables in sysconfig directory's
console, network, and clock files to be placed in rc.site.

Add an optional FASTBOOT parameter to set /fastboot when rebooting.

Remove a minor warning message from udev that is triggered
by the udev_retry boot script.

Add SKIPTMPCLEAN as an optional parameter to skip cleaning /tmp at boot time.

Add a page to Chapter 7 documenting rc.site.

diff --git a/bootscripts/lfs/init.d/consolelog b/bootscripts/lfs/init.d/consolelog
--- a/bootscripts/lfs/init.d/consolelog
+++ b/bootscripts/lfs/init.d/consolelog
@@ -5,7 +5,8 @@
 # Description : Set the kernel log level for the console
 #
 # Authors     : Dan Nicholson - dnicholson@linuxfromscratch.org
-# Authors     : Gerard Beekmans  - gerard@linuxfromscratch.org
+#               Gerard Beekmans  - gerard@linuxfromscratch.org
+#               DJ Lucas - dj@linuxfromscratch.org
 # Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #
 # Version     : LFS 7.0
@@ -27,25 +28,28 @@
 # X-LFS-Provided-By:   LFS
 ### END INIT INFO
 
-. /lib/boot/functions
+. /lib/lsb/init-functions
 
-# set the default loglevel
-LOGLEVEL=7
+# set the default loglevel if needed
+LOGLEVEL=${LOGLEVEL:-7}
 
-[ -r /etc/sysconfig/console ] &&  . /etc/sysconfig/console
+[ -r /etc/sysconfig/console ] && . /etc/sysconfig/console
 
 case "${1}" in
    start)
       case "$LOGLEVEL" in
       [1-8])
-         boot_mesg "Setting the console log level to ${LOGLEVEL}..."
+         log_info_msg "Setting the console log level to ${LOGLEVEL}..."
          dmesg -n $LOGLEVEL
          evaluate_retval
+         exit 0
          ;;
+
       *)
-         boot_mesg "Console log level '${LOGLEVEL}' is invalid" ${FAILURE}
-         echo_failure
+         log_failure_msg "Console log level '${LOGLEVEL}' is invalid"
+         exit 1
          ;;
+      
       esac
       ;;
 
@@ -54,13 +58,14 @@ case "${1}" in
       if [ -r /proc/sys/kernel/printk ]; then
          read level line < /proc/sys/kernel/printk
       else
-         boot_mesg "Can't read the current console log level" ${FAILURE}
-         echo_failure
+         log_failure_msg "Can't read the current console log level"
+         exit 1
       fi
 
       # Print the value
       if [ -n "$level" ]; then
-         ${ECHO} -e "${INFO}The current console log level is ${level}${NORMAL}"
+         log_info_msg "The current console log level is ${level}\n"
+         exit 0
       fi
       ;;
 
