Rewrite bootscripts and Chaper 7

diff --git a/trunk/BOOK/bootscripts/lfs/init.d/console b/trunk/BOOK/bootscripts/lfs/init.d/console
--- a/trunk/BOOK/bootscripts/lfs/init.d/console
+++ b/trunk/BOOK/bootscripts/lfs/init.d/console
@@ -1,96 +1,107 @@
 #!/bin/sh
 ########################################################################
-# Begin $rc_base/init.d/console
+# Begin console
 #
 # Description : Sets keymap and screen font
 #
 # Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
-#		Alexander E. Patrakov
+#               Alexander E. Patrakov
+# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #
-# Version     : 00.03
-#
-# Notes       :
+# Version     : LFS 7.0
 #
 ########################################################################
 
-. /etc/sysconfig/rc
-. ${rc_functions}
+. /lib/boot/functions
+
+### BEGIN INIT INFO
+# Provides:            console
+# Required-Start:
+# Should-Start:        $local_fs
+# Required-Stop:
+# Should-Stop:
+# Default-Start:       S
+# Default-Stop:
+# Short-Description:   Sets up a localised console.
+# Description:         Sets up fonts and language settings for the user's
+#                      local as defined by /etc/sysconfig/console.
+# X-LFS-Provided-By:   LFS
+### END INIT INFO
 
 # Native English speakers probably don't have /etc/sysconfig/console at all
-if [ -f /etc/sysconfig/console ]
-then
-	. /etc/sysconfig/console
+if [ -r /etc/sysconfig/console ]; then
+   . /etc/sysconfig/console
 else
-        exit 0
+   exit 0
 fi
 
 is_true() {
-	[ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ]
+   [ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ]
 }
 
 failed=0
 
 case "${1}" in
-	start)
-		boot_mesg "Setting up Linux console..."
-		# There should be no bogus failures below this line!
-		
-		# Figure out if a framebuffer console is used
-		[ -d /sys/class/graphics/fb0 ] && USE_FB=1 || USE_FB=0
-		
-		# Figure out the command to set the console into the
-		# desired mode
-		is_true "${UNICODE}" &&
-			MODE_COMMAND="${ECHO} -en '\033%G' && kbd_mode -u" ||
-			MODE_COMMAND="${ECHO} -en '\033%@\033(K' && kbd_mode -a"
-		
-		# On framebuffer consoles, font has to be set for each vt in
-		# UTF-8 mode. This doesn't hurt in non-UTF-8 mode also.
-		
-		! is_true "${USE_FB}" || [ -z "${FONT}" ] ||
-			MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"
+   start)
+      boot_mesg "Setting up Linux console..."
+      # There should be no bogus failures below this line!
 
-		# Apply that command to all consoles mentioned in
-		# /etc/inittab. Important: in the UTF-8 mode this should
-		# happen before setfont, otherwise a kernel bug will
-		# show up and the unicode map of the font will not be
-		# used.
-		# FIXME: Fedora Core also initializes two spare consoles
-		# - do we want that?
-		
-		for TTY in `grep '^[^#].*respawn:/sbin/agetty' /etc/inittab |
-			grep -o '\btty[[:digit:]]*\b'`
-		do
-			openvt -f -w -c ${TTY#tty} -- \
-				/bin/sh -c "${MODE_COMMAND}" || failed=1
-		done
+      # Figure out if a framebuffer console is used
+      [ -d /sys/class/graphics/fb0 ] && USE_FB=1 || USE_FB=0
 
-		# Set the font (if not already set above) and the keymap
-		is_true "${USE_FB}" || [ -z "${FONT}" ] ||
-			setfont $FONT ||
-			failed=1
-		[ -z "${KEYMAP}" ] ||
-			loadkeys ${KEYMAP} >/dev/null 2>&1 ||
-			failed=1
-		[ -z "${KEYMAP_CORRECTIONS}" ] ||
-			loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 ||
-			failed=1
+      # Figure out the command to set the console into the
+      # desired mode
+      is_true "${UNICODE}" &&
+         MODE_COMMAND="${ECHO} -en '\033%G' && kbd_mode -u" ||
+         MODE_COMMAND="${ECHO} -en '\033%@\033(K' && kbd_mode -a"
 
-		# Convert the keymap from $LEGACY_CHARSET to UTF-8
-		[ -z "$LEGACY_CHARSET" ] ||
-			dumpkeys -c "$LEGACY_CHARSET" |
-			loadkeys -u >/dev/null 2>&1 ||
-			failed=1
+      # On framebuffer consoles, font has to be set for each vt in
+      # UTF-8 mode. This doesn't hurt in non-UTF-8 mode also.
 
-		# If any of the commands above failed, the trap at the
-		# top would set $failed to 1
-		( exit $failed )
-		evaluate_retval
-		;;
-	*)
-		echo $"Usage:" "${0} {start}"
-		exit 1
-		;;
+      ! is_true "${USE_FB}" || [ -z "${FONT}" ] ||
+         MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"
+
+      # Apply that command to all consoles mentioned in
+      # /etc/inittab. Important: in the UTF-8 mode this should
+      # happen before setfont, otherwise a kernel bug will
+      # show up and the unicode map of the font will not be
+      # used.
+      # FIXME: Fedora Core also initializes two spare consoles
+      # - do we want that?
+
+      for TTY in `grep '^[^#].*respawn:/sbin/agetty' /etc/inittab |
+         grep -o '\btty[[:digit:]]*\b'`
+      do
+         openvt -f -w -c ${TTY#tty} -- \
+            /bin/sh -c "${MODE_COMMAND}" || failed=1
+      done
+
+      # Set the font (if not already set above) and the keymap
+      is_true "${USE_FB}" || [ -z "${FONT}" ] ||
+         setfont $FONT ||
+         failed=1
+      [ -z "${KEYMAP}" ] ||
+         loadkeys ${KEYMAP} >/dev/null 2>&1 ||
+         failed=1
+      [ -z "${KEYMAP_CORRECTIONS}" ] ||
+         loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 ||
+         failed=1
+
+      # Convert the keymap from $LEGACY_CHARSET to UTF-8
+      [ -z "$LEGACY_CHARSET" ] ||
+         dumpkeys -c "$LEGACY_CHARSET" |
+         loadkeys -u >/dev/null 2>&1 ||
+         failed=1
+
+      # If any of the commands above failed, the trap at the
+      # top would set $failed to 1
+      ( exit $failed )
+      evaluate_retval
+      ;;
+   *)
+      echo $"Usage:" "${0} {start}"
+      exit 1
+      ;;
 esac
 
-# End $rc_base/init.d/console
+# End console
diff --git a/trunk/BOOK/bootscripts/lfs/init.d/rc b/trunk/BOOK/bootscripts/lfs/init.d/rc
--- a/trunk/BOOK/bootscripts/lfs/init.d/rc
+++ b/trunk/BOOK/bootscripts/lfs/init.d/rc
@@ -1,19 +1,52 @@
 #!/bin/sh
 ########################################################################
-# Begin $rc_base/init.d/rc
+# Begin rc
 #
 # Description : Main Run Level Control Script
 #
 # Authors     : Gerard Beekmans  - gerard@linuxfromscratch.org
+# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #
-# Version     : 00.00
-#
-# Notes       :
+# Version     : LFS 7.0
 #
 ########################################################################
 
-. /etc/sysconfig/rc
-. ${rc_functions}
+. /lib/boot/functions
+
+print_error_msg()
+{
+   echo_failure
+   # $i is set when called
+   boot_mesg -n "FAILURE:\n\nYou should not be reading this error message.\n\n" ${FAILURE}
+   boot_mesg -n " It means that an unforeseen error took"
+   boot_mesg -n " place in ${i}, which exited with a return value of"
+   boot_mesg " ${error_value}.\n"
+   boot_mesg_flush
+   boot_mesg -n "If you're able to track this"
+   boot_mesg -n " error down to a bug in one of the files provided by"
+   boot_mesg -n " the LFS book, please be so kind to inform us at"
+   boot_mesg " lfs-dev@linuxfromscratch.org.\n"
+   boot_mesg_flush
+   boot_mesg -n "Press Enter to continue..." ${INFO}
+   boot_mesg "" ${NORMAL}
+   wait_for_user
+}
+
+check_script_status()
+{
+   # $i is set when called
+   if [ ! -f ${i} ]; then
+      boot_mesg "${i} is not a valid symlink." ${WARNING}
+      echo_warning
+      continue
+   fi
+
+   if [ ! -x ${i} ]; then
+      boot_mesg "${i} is not executable, skipping." ${WARNING}
+      echo_warning
+      continue
+   fi
+}
 
 # This sets a few default terminal options.
 stty sane
@@ -24,76 +57,77 @@ trap "" INT QUIT TSTP
 [ "${1}" != "" ] && runlevel=${1}
 
 if [ "${runlevel}" = "" ]; then
-	echo "Usage: ${0} <runlevel>" >&2
-	exit 1
+   echo "Usage: ${0} <runlevel>" >&2
+   exit 1
 fi
 
 previous=${PREVLEVEL}
 [ "${previous}" = "" ] && previous=N
 
-if [ ! -d ${rc_base}/rc${runlevel}.d ]; then
-	boot_mesg "${rc_base}/rc${runlevel}.d does not exist." ${WARNING}
-	boot_mesg_flush
-	exit 1
+if [ ! -d /etc/rc.d/rc${runlevel}.d ]; then
+   boot_mesg "/etc/rc.d/rc${runlevel}.d does not exist." 
+   exit 1
 fi
 
-# Attempt to stop all service started by previous runlevel,
+# Attempt to stop all services started by the previous runlevel,
 # and killed in this runlevel
 if [ "${previous}" != "N" ]; then
-	for i in $(ls -v ${rc_base}/rc${runlevel}.d/K* 2> /dev/null)
-	do
-		check_script_status
+   for i in $(ls -v /etc/rc.d/rc${runlevel}.d/K* 2> /dev/null)
+   do
+      check_script_status
 
-		suffix=${i#$rc_base/rc$runlevel.d/K[0-9][0-9]}
-		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
-		sysinit_start=$rc_base/rcsysinit.d/S[0-9][0-9]$suffix
+      suffix=${i#/etc/rc.d/rc$runlevel.d/K[0-9][0-9]}
+      prev_start=/etc/rc.d/rc$previous.d/S[0-9][0-9]$suffix
+      sysinit_start=/etc/rc.d/rcsysinit.d/S[0-9][0-9]$suffix
 
-		if [ "${runlevel}" != "0" ] && [ "${runlevel}" != "6" ]; then
-			if [ ! -f ${prev_start} ] && [ ! -f ${sysinit_start} ]; then
-				boot_mesg -n "WARNING:\n\n${i} can't be" ${WARNING}
-				boot_mesg -n " executed because it was not"
-				boot_mesg -n " not started in the previous"
-				boot_mesg -n " runlevel (${previous})."
-				boot_mesg "" ${NORMAL}
-				boot_mesg_flush
-				continue
-			fi
-		fi
-		${i} stop
-		error_value=${?}
+      if [ "${runlevel}" != "0" ] && [ "${runlevel}" != "6" ]; then
+         if [ ! -f ${prev_start} ] && [ ! -f ${sysinit_start} ]; then
+            boot_mesg -n "WARNING:\n\n${i} can't be" ${WARNING}
+            boot_mesg -n " executed because it was not"
+            boot_mesg -n " not started in the previous"
+            boot_mesg -n " runlevel (${previous})."
+            boot_mesg "" ${NORMAL}
+            boot_mesg_flush
+            continue
+         fi
+      fi
+      ${i} stop
+      error_value=${?}
 
-		if [ "${error_value}" != "0" ]; then
-			print_error_msg
-		fi
-	done
+      if [ "${error_value}" != "0" ]; then
+         print_error_msg
+      fi
+   done
 fi
 
+[ "${previous}" = "N" ] && IN_BOOT=1
+
 #Start all functions in this runlevel
-for i in $( ls -v ${rc_base}/rc${runlevel}.d/S* 2> /dev/null)
+for i in $( ls -v /etc/rc.d/rc${runlevel}.d/S* 2> /dev/null)
 do
-	if [ "${previous}" != "N" ]; then
-		suffix=${i#$rc_base/rc$runlevel.d/S[0-9][0-9]}
-		stop=$rc_base/rc$runlevel.d/K[0-9][0-9]$suffix
-		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
+   if [ "${previous}" != "N" ]; then
+      suffix=${i#/etc/rc.d/rc$runlevel.d/S[0-9][0-9]}
+      stop=/etc/rc.d/rc$runlevel.d/K[0-9][0-9]$suffix
+      prev_start=/etc/rc.d/rc$previous.d/S[0-9][0-9]$suffix
 
-		[ -f ${prev_start} ] && [ ! -f ${stop} ] && continue
-	fi
+      [ -f ${prev_start} ] && [ ! -f ${stop} ] && continue
+   fi
 
-	check_script_status
+   check_script_status
 
-	case ${runlevel} in
-		0|6)
-			${i} stop
-			;;
-		*)
-			${i} start
-			;;
-	esac
-	error_value=${?}
+   case ${runlevel} in
+      0|6)
+         ${i} stop
+         ;;
+      *)
+         ${i} start
+         ;;
+   esac
+   error_value=${?}
 
-	if [ "${error_value}" != "0" ]; then
-		print_error_msg
-	fi
+   if [ "${error_value}" != "0" ]; then
+      print_error_msg
+   fi
 done
 
-# End $rc_base/init.d/rc
+# End rc
diff --git a/trunk/BOOK/bootscripts/lfs/init.d/udev_retry b/trunk/BOOK/bootscripts/lfs/init.d/udev_retry
--- a/trunk/BOOK/bootscripts/lfs/init.d/udev_retry
+++ b/trunk/BOOK/bootscripts/lfs/init.d/udev_retry
@@ -1,45 +1,60 @@
 #!/bin/sh
 ########################################################################
-# Begin $rc_base/init.d/udev_retry
+# Begin udev_retry
 #
 # Description : Udev cold-plugging script (retry)
 #
 # Authors     : Alexander E. Patrakov
+# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #
-# Version     : 00.02
-#
-# Notes       :
+# Version     : LFS 7.0
 #
 ########################################################################
 
-. /etc/sysconfig/rc
-. ${rc_functions}
+### BEGIN INIT INFO
+# Provides:            udev_retry
+# Required-Start:      udev
+# Should-Start:        $local_fs
+# Required-Stop:
+# Should-Stop:
+# Default-Start:       S
+# Default-Stop:
+# Short-Description:   Replays failed uevents and creates additonal devices.
+# Description:         Replays any failed uevents that were skipped due to
+#                      slow hardware initialization, and creates those needed
+#                      device nodes
+# X-LFS-Provided-By:   LFS
+### END INIT INFO
+
+. /lib/boot/functions
 
 case "${1}" in
-	start)
-		boot_mesg "Retrying failed uevents, if any..."
+   start)
+      boot_mesg "Retrying failed uevents, if any..."
 
-		# From Debian: "copy the rules generated before / was mounted
-		# read-write":
-		for file in /dev/.udev/tmp-rules--*; do
-			dest=${file##*tmp-rules--}
-			[ "$dest" = '*' ] && break
-			cat $file >> /etc/udev/rules.d/$dest
-			rm -f $file
-		done
+      RUNDIR=$(/sbin/udevadm info --run)
+      # From Debian: "copy the rules generated before / was mounted
+      # read-write":
+    
+      for file in ${RUNDIR}/tmp-rules--*; do
+         dest=${file##*tmp-rules--}
+         [ "$dest" = '*' ] && break
+         cat $file >> /etc/udev/rules.d/$dest
+         rm -f $file
+      done
 
-		# Re-trigger the failed uevents in hope they will succeed now
-		/sbin/udevadm trigger --type=failed --action=add
-		
-		# Now wait for udevd to process the uevents we triggered
-		/sbin/udevadm settle
-		evaluate_retval
-		;;
+      # Re-trigger the failed uevents in hope they will succeed now
+      /sbin/udevadm trigger --type=failed --action=add
 
-	*)
-		echo "Usage ${0} {start}"
-		exit 1
-		;;
+      # Now wait for udevd to process the uevents we triggered
+      /sbin/udevadm settle
+      evaluate_retval
+      ;;
+
+   *)
+      echo "Usage ${0} {start}"
+      exit 1
+      ;;
 esac
 
-# End $rc_base/init.d/udev_retry
+# End udev_retry
